In [1]:
import requests
import pandas as pd

In [4]:
response = requests.get("https://jsonplaceholder.typicode.com/users")
data = response.json()
response.status_code

200

In [5]:
type(data)

list

In [ ]:
df = pd.DataFrame(data)
df.head(10)

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [9]:
data[0]

{'id': 1,
 'name': 'Leanne Graham',
 'username': 'Bret',
 'email': 'Sincere@april.biz',
 'address': {'street': 'Kulas Light',
  'suite': 'Apt. 556',
  'city': 'Gwenborough',
  'zipcode': '92998-3874',
  'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
 'phone': '1-770-736-8031 x56442',
 'website': 'hildegard.org',
 'company': {'name': 'Romaguera-Crona',
  'catchPhrase': 'Multi-layered client-server neural-net',
  'bs': 'harness real-time e-markets'}}

In [12]:
df.columns

Index(['id', 'name', 'username', 'email', 'address', 'phone', 'website',
       'company'],
      dtype='str')

In [18]:
df.iloc[0,1]

'Leanne Graham'

In [23]:
df.loc[0:5,["name","address"]]

                   name                                            address
0         Leanne Graham  {'street': 'Kulas Light', 'suite': 'Apt. 556',...
1          Ervin Howell  {'street': 'Victor Plains', 'suite': 'Suite 87...
2      Clementine Bauch  {'street': 'Douglas Extension', 'suite': 'Suit...
3      Patricia Lebsack  {'street': 'Hoeger Mall', 'suite': 'Apt. 692',...
4      Chelsey Dietrich  {'street': 'Skiles Walks', 'suite': 'Suite 351...
5  Mrs. Dennis Schulist  {'street': 'Norberto Crossing', 'suite': 'Apt....

In [37]:
data_1 = requests.get("https://jsonplaceholder.typicode.com/users", params={"id": [1,2,3,4,5]})
r = data_1.json()
print("length of data_1:", len(r))
r[0]

length of data_1: 5

{'id': 1,
 'name': 'Leanne Graham',
 'username': 'Bret',
 'email': 'Sincere@april.biz',
 'address': {'street': 'Kulas Light',
  'suite': 'Apt. 556',
  'city': 'Gwenborough',
  'zipcode': '92998-3874',
  'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
 'phone': '1-770-736-8031 x56442',
 'website': 'hildegard.org',
 'company': {'name': 'Romaguera-Crona',
  'catchPhrase': 'Multi-layered client-server neural-net',
  'bs': 'harness real-time e-markets'}}

In [38]:
API_KEY = "b238da37213d7fa7c9edc37eec6312a5"

In [41]:
city = "Karachi"
url = 'https://api.openweathermap.org/data/2.5/weather'
params = {"q": city, "appid": API_KEY, "units": "metric"}
res = requests.get(url, params=params)
res.status_code

200

In [42]:
weather_data = res.json()
weather_data

{'coord': {'lon': 67.0822, 'lat': 24.9056},
 'weather': [{'id': 500,
   'main': 'Rain',
   'description': 'light rain',
   'icon': '10n'}],
 'base': 'stations',
 'main': {'temp': 29.9,
  'feels_like': 35.77,
  'temp_min': 29.9,
  'temp_max': 29.9,
  'pressure': 1008,
  'humidity': 74,
  'sea_level': 1008,
  'grnd_level': 1004},
 'visibility': 10000,
 'wind': {'speed': 5.66, 'deg': 240},
 'rain': {'1h': 0.87},
 'clouds': {'all': 100},
 'dt': 1789401579,
 'sys': {'type': 1,
  'id': 7576,
  'country': 'PK',
  'sunrise': 1789348639,
  'sunset': 1789393064},
 'timezone': 18000,
 'id': 1174872,
 'name': 'Karachi',
 'cod': 200}