In [2]:
order = [{"Customer_name": "Ali", "Sales": 201, "Region": "Central"},
         {"Customer_name": "Hassan", "Sales": 101, "Region": "West"},
         {"Customer_name": "Hussain", "Sales": 301, "Region": "North"}]

In [3]:
import pandas as pd
df = pd.DataFrame(order)

In [4]:
print(df)

  Customer_name  Sales   Region
0           Ali    201  Central
1        Hassan    101     West
2       Hussain    301    North

In [7]:
df1 = pd.read_csv("superstore.csv");
print(df1.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045
3       4  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335

     Customer Name    Segment             City       State Region  \
0      Claire Gute   Consumer        Henderson    Kentucky  South
1      Claire Gute   Consumer        Henderson    Kentucky  South
2  Darrin Van Huff  Corporate      Los Angeles  California   West
3   Sean O'Donnell   Consumer  Fort Lauderdale     Florida  South
4   Sean O'Donnell   Consumer  Fort Lauderdale     Florida  South

        Product ID         Category Sub-Category  \
0  FUR-BO-10001798        Furniture    Bookcases
1  FUR-CH-10000454        Furniture       Chairs
2  OFF-LA-10000240  Office Supplies       Labels
3  FUR-TA-10000577        Furniture       Tables
4  OFF-ST-10000760  Office Supplies          NaN

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600       2.0
1      Hon Deluxe Fabric Upholstered Stacking Chairs  731.9400       3.0
2  Self-Adhesive Address Labels for Typewriters b...   14.6200       2.0
3      Bretford CR4500 Series Slim Rectangular Table  957.5775       5.0
4                     Eldon Fold 'N Roll Cart System   22.3680       2.0

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

In [27]:
df1[["Sales","Customer Name", "City"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales          180 non-null    float64
 1   Customer Name  180 non-null    str
 2   City           180 non-null    str
dtypes: float64(1), str(2)
memory usage: 4.3 KB

In [29]:
sale = [234.456 , 764]
print(sale)

[234.456, 764]

In [32]:
for i in sale:
    tax_ret = i * 1.25
    print(f"this is the old {i} and this is new {tax_ret}")

this is the old 234.456 and this is new 293.07
this is the old 764 and this is new 955.0

In [33]:
taxed_sale = (df1["Sales"] * 1.25)
print(df1["Sales"])

0      261.9600
1      731.9400
2       14.6200
3      957.5775
4       22.3680
         ...
175     20.1600
176     97.2640
177    396.8020
178     15.8800
179      3.2800
Name: Sales, Length: 180, dtype: float64

In [34]:
print(taxed_sale)

0       327.450000
1       914.925000
2        18.275000
3      1196.971875
4        27.960000
          ...
175      25.200000
176     121.580000
177     496.002500
178      19.850000
179       4.100000
Name: Sales, Length: 180, dtype: float64

In [35]:
print(df1["Sales"].sum())

44680.5977

In [38]:
print(df1["Sales"].min())

1.248

In [ ]:
df1["Sales"] > 1000

0      False
1      False
2      False
3      False
4      False
       ...
175    False
176    False
177    False
178    False
179    False
Name: Sales, Length: 180, dtype: bool

In [ ]:
df1[df1["Sales"] > 1000]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10,11,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9.0,0.2,85.3092
24,25,CA-2015-106320,2015-09-25,2015-09-30,Standard Class,EB-13870,Emily Burns,Consumer,Orem,Utah,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3.0,0.0,240.2649
27,28,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,Jackson,Michigan,Central,FUR-BO-10004834,Furniture,Bookcases,Riverside Palais Royal Lawyers Bookcase,3083.430,7.0,0.5,-1665.0522
35,36,CA-2016-117590,2016-12-08,2016-12-10,First Class,GH-14485,Gene Hale,Corporate,Richardson,Texas,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7.0,0.2,123.4737
54,55,CA-2016-105816,2016-12-11,2016-12-17,Standard Class,JM-15265,Janet Molinari,Corporate,New York City,New York,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5.0,0.0,298.6855
67,68,CA-2014-106376,2014-12-05,2014-12-10,Standard Class,BS-11590,Brendan Sweed,Corporate,Gilbert,Arizona,West,OFF-AR-10002671,Office Supplies,Art,Hunt BOSTON High-Volume Electric Pencil Sharpener,1113.024,8.0,0.2,111.3024
149,150,CA-2016-114489,2016-12-05,2016-12-09,Standard Class,JE-16165,Justin Ellison,Corporate,Franklin,Wisconsin,Central,FUR-CH-10000454,Furniture,Chairs,Hon Deluxe Fabric Upholstered Stacking Chairs,1951.840,8.0,0.0,585.5520
165,166,CA-2014-139892,2014-09-08,2014-09-12,Standard Class,BM-11140,Becky Martin,Consumer,San Antonio,Texas,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,8159.952,8.0,0.4,-1359.9920
167,168,CA-2014-139892,2014-09-08,2014-09-12,Standard Class,BM-11140,Becky Martin,Consumer,San Antonio,Texas,Central,FUR-CH-10004287,Furniture,Chairs,SAFCO Arco Folding Chair,1740.060,9.0,0.3,-24.8580

In [42]:
df1[df1["Region"] == "West"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2.0,0.0,6.8714
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,NaN,0.0,14.1694
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4.0,0.0,1.9656
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,NaN,Brosina Hoffman,Consumer,Los Angeles,California,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6.0,0.2,90.7152
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings,18.504,3.0,0.2,5.7825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,163,CA-2016-154508,2016-11-16,2016-11-20,Standard Class,RD-19900,Ruben Dartt,Consumer,Carlsbad,New Mexico,West,OFF-EN-10001990,Office Supplies,Envelopes,Staple envelope,28.400,5.0,0.0,13.3480
163,164,CA-2016-113817,2016-11-07,2016-11-11,Standard Class,MJ-17740,Max Jones,Consumer,Seattle,Washington,West,OFF-BI-10004002,Office Supplies,Binders,Wilson Jones International Size A4 Ring Binders,27.680,2.0,0.2,9.6880
171,172,CA-2014-118962,2014-08-05,2014-08-09,Standard Class,CS-12130,Chad Sievert,Consumer,Los Angeles,California,West,OFF-PA-10000659,Office Supplies,Paper,Adams Phone Message Book Professional,20.940,3.0,0.0,9.8418
172,173,CA-2014-118962,2014-08-05,2014-08-09,Standard Class,CS-12130,Chad Sievert,Consumer,Los Angeles,California,West,OFF-PA-10001144,Office Supplies,Paper,Xerox 1913,110.960,2.0,0.0,53.2608
173,174,CA-2014-118962,2014-08-05,2014-08-09,Standard Class,CS-12130,Chad Sievert,Consumer,Los Angeles,California,West,FUR-CH-10003817,Furniture,Chairs,Global Value Steno Chair Gray,340.144,7.0,0.2,21.2590

In [44]:
df[(df["Region"] == "West") & (df["Sales"] > 500)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,NaN,Brosina Hoffman,Consumer,Los Angeles,California,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6.0,0.2,90.7152
10,11,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9.0,0.2,85.3092
11,12,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,Los Angeles,California,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.424,4.0,0.2,68.3568
24,25,CA-2015-106320,2015-09-25,2015-09-30,Standard Class,EB-13870,Emily Burns,Consumer,Orem,Utah,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3.0,0.0,240.2649
67,68,CA-2014-106376,2014-12-05,2014-12-10,Standard Class,BS-11590,Brendan Sweed,Corporate,Gilbert,Arizona,West,OFF-AR-10002671,Office Supplies,Art,Hunt BOSTON High-Volume Electric Pencil Sharpener,1113.024,8.0,0.2,111.3024
117,118,CA-2015-110457,2015-03-02,2015-03-06,Standard Class,DK-13090,Dave Kipp,Consumer,Seattle,Washington,West,FUR-TA-10001768,Furniture,Tables,Hon Racetrack Conference Tables,787.530,3.0,0.0,165.3813
145,146,CA-2015-110744,2015-09-07,2015-09-12,Standard Class,HA-14920,Helen Andreada,Consumer,Pasadena,California,West,OFF-ST-10003656,Office Supplies,Storage,Safco Industrial Wire Shelving,671.930,7.0,0.0,20.1579

In [45]:
df["Region"].value_counts()

Region
Central    65
West       62
East       37
South      16
Name: count, dtype: int64

In [46]:
#fetch specific product id
df[df["Product ID"] == "TEC-PH-10002275"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,NaN,Brosina Hoffman,Consumer,Los Angeles,California,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6.0,0.2,90.7152